### PR TITLE
Migrate to Fody 3.1.4

### LINKED ISSUE #1: Update to use latest version of Fody
@adbancroft it's a cool weaver, however it's no longer usable with the latest version of Fody.

### PR DESCRIPTION
**Pull request by tom-englert**
Fixes #1

### CODE REVIEW

**Comment by tom-englert** [comment]
@adbancroft any chance to get this merged/released? Is this project still alive?

**Comment by adbancroft** [comment]
Working on it. Initial eyeball review of your changes look OK, but I have new PC which is blocking me building :-(

**Comment by tom-englert** [comment]
Any update on this?

**Comment by adbancroft** [comment]
Your PR doesn't build for me - the Mono.Cecil NuGet package has been removed?

**Comment by tom-englert** [comment]
Yes, Mono.Cecil is now part of FodyHelpers. What errors do you get?

**Comment by adbancroft** [comment]
Ah, I see the issue: I'm using VS2015 which I don't think supports PackageReference.

**Comment by adbancroft** [comment]
VS2017 installed - builds OK now.

**Review by adbancroft — APPROVED** [review]

**Pull request merged**
